version: "3.5"
services:
  discordbot:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: ./.env
    restart: always
    volumes:
      - ./app:/application
    environment:
      - "NODE_ENV=development"
    command: ["yarn", "dev"]
