version: "3.5"
services:
  discordbot:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - /app/database:/application/database
    environment:
      - "NODE_ENV=production"
    restart: always
